import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import "./globals.css";

export const metadata = {
  title: "Pindie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Header/>

        {children}

        <Footer/>
      </body>
    </html>
  );
}


// 1) Шрифты неправильно отображаются.
// 2) Footer тоже неправильно отображается. Не знаю в чем проблема, но отличается от HTML документа(исходника)